config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'readers/home#index'
  get '/blog/:id' => 'readers/posts#show', as: :blog_post

  scope module: 'authors' do
    resources :posts do
      resources :elements
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_authors_on_email                 (email) UNIQUE
#  index_authors_on_reset_password_token  (reset_password_token) UNIQUE
#
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
end

app/models/element.rb
# == Schema Information
#
# Table name: elements
#
#  id           :integer          not null, primary key
#  element_type :string
#  position     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  post_id      :integer          not null
#
# Indexes
#
#  index_elements_on_post_id  (post_id)
#
# Foreign Keys
#
#  post_id  (post_id => posts.id)
#
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-embed'] }

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  description  :text
#  published    :boolean
#  published_at :datetime
#  slug         :string
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  author_id    :integer          not null
#
# Indexes
#
#  index_posts_on_author_id  (author_id)
#  index_posts_on_slug       (slug) UNIQUE
#
# Foreign Keys
#
#  author_id  (author_id => authors.id)
#
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author
  has_many :elements

  has_one_attached :header_image

  scope :published, -> do
    where(published: true)
  end

  scope :most_recently_published, -> do
    order(published_at: :desc)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: %i[ update destroy ]

    # POST /elements
    def create
      @element = @post.elements.build(element_params)

      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.join(". ") << "."
      end
      redirect_to edit_post_path(@post), notice: notice
    end

    # PATCH/PUT /elements/1 or /elements/1.json
    def update
      @element.update(element_params)
      redirect_to edit_post_path(@element.post)
    end

    # DELETE /elements/1 or /elements/1.json
    def destroy
      @element.destroy
      redirect_to edit_post_path(@element.post)
    end

    private

      def set_post
        @post = current_author.posts.friendly.find(params[:post_id])
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_element
        @element = @post.elements.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def element_params
        params.require(:element).permit(:element_type, :content, :image)
      end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: %i[ edit update destroy ]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /posts or /posts.json
    def create
      @post = current_author.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        render :edit
      end
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy
      redirect_to posts_url
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/readers/home_controller.rb
module Readers
  class HomeController < ReadersController
    def index
      @posts = Post.published.most_recently_published
    end
  end
end

app/controllers/readers/posts_controller.rb
module Readers
  class PostsController < ReadersController
    def show
      @post = Post.published.friendly.find(params[:id])
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  layout 'readers'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group m-2">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control m-2" %>
  </div>

  <div class="form-group m-2">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control m-2" %>
  </div>

   <div class="form-group m-2">
    <%= form.label :header_image %>
    <%= form.file_field :header_image, class: "form-control m-2" %>
    <div class='mt-3'>
    <% if post.header_image.present? %>
      <small>Current Image:</small>
      <%= image_tag(post.header_image, width: '100%') %>
    <% end %>
    </div>
  </div>

  <div class="actions d-grid gap-*">
    <%= form.submit class: "btn btn-primary m-2" %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class='row'>
  <div class='col-md-4'>
    <%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe, posts_path, class: 'btn btn-dark mb-3 text-light' %>
    <div class='card'>
      <div class='card-header'>
        <h6 class='card-title mb-0'>Edit Post</h6>
      </div>
      <div class='card-body'>
        <%= render 'form', post: @post %>
      </div>
      <div class='card-footer'>
        <% if @post.published? %>
          <a href="#" 
            class='btn btn-secondary d-grid gap-*' data-reflex='click->PublisherReflex#unpublish' 
            data-post-id='<%= @post.id %>'>
            Unpublish
          </a>
        <% else %>
          <a href="#" 
            class='btn btn-dark d-grid gap-*' 
            data-reflex='click->PublisherReflex#publish' 
            data-post-id='<%= @post.id %>'>
            Publish
          </a>
        <% end %>
      </div>
    </div>
  </div>
  <div class='col-md-8'>
    <div class='mb-3 d-flex justify-content-end'>
      <%= form_with(model: [@post, @element], class: 'me-3') do |form| %>
        <%= form.hidden_field :element_type, value: 'paragraph' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class="fas fa-paragraph"></i>
        <% end %>
      <% end %>
      <%= form_with(model: [@post, @element]) do |form| %>
        <%= form.hidden_field :element_type, value: 'image' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class="fas fa-image"></i>
        <% end %>
      <% end %>
    </div>
    <div class='card mb-5'>
      <div class='card-header text-end'>
       <% if @post.published? %>
          Published <%= time_ago_in_words(@post.published_at) %> ago
        <% else %>
          Unpublished
        <% end %>
      </div>
      <div class='card-body pt-5' data-controller='elements'>
        <% if @post.elements.none? { |element| element.persisted? } %>
          <div class='text-center p-4'>
            <h2 class='text-secondary'>
              <i class="far fa-question-circle"></i>
            </h2>
            <div class='text-secondary'>
              <p>Add text and pictures using the buttons above</p>
            </div>
          </div>
        <% else %>
          <ul id='elements' data-action='drop->elements#sort'>
            <% @post.elements.order(position: :asc).each do |element| %>
              <% if element.persisted? %>
                <li data-id='<%= element.id %>' class='element-item'>
                  <% if element.paragraph? %>
                    <div class='mb-4 p-3 paragraph'>
                      <div class='paragraph-content'>
                        <% if element.content.present?%>
                          <%= element.content %>
                        <% else %>
                          Click to add text 
                        <% end %>
                      </div>
                      <div class='paragraph-form d-none'>
                        <%= form_with(model: [@post, element]) do |form| %>
                          <%= form.rich_text_area :content %>
                          <div class='mt-3 d-flex justify-content-between'>
                            <div>
                              <%= form.submit 'Save', class: 'btn btn-primary'%>
                              <a href="#" class='cancel btn btn-secondary'>Cancel</a>
                            </div>
                            <%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  <% elsif element.image? %>
                    <div class='image'>
                      <% if element.image.present? %>
                        <%= link_to post_element_path(@post, element), method: :delete, class: 'delete-btn float-end btn btn-dark mt-2', data: { confirm: 'Are you sure?' } do %>
                          <i class='fas fa-times'></i>
                        <% end %>
                        <%= image_tag(element.image) %>
                      <% else %>
                        <%= form_with(model: [@post, element]) do |form| %>
                          <%= form.file_field :image %>
                          <div class='mt-3'>
                            <%= form.submit 'Save', class: 'btn btn-primary'%>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/posts/index.html.erb
<h4 id="elements" class='d-flex justify-content-between mb-4'>
  <div><%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe, root_path, class: 'btn btn-dark mb-3 text-light' %></div>
  <span>My Posts</span>
  <div>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary text-light' %>
  </div>
</h4>

<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
    <div class='card mb-3 post-card'>
      <div class='card-body'>
        <div class='row'>
          <div class='col-md-2'>
            <% if post.header_image.present? %>
              <div class='header-img' style='background-image: url(<%= url_for(post.header_image) %>);'></div>
            <% end %>
          </div>
          <div class='col-md-10'>
          <% if post.published? %>
            <span class='badge bg-primary float-end'>Published</span>
          <% else %>
            <span class='badge bg-danger float-end'>Unpublished</span>
          <% end %>
            <h5 class='card-title mb-2 text-dark'><%= post.title %></h5>
            <p class='text-secondary mb-0'><%= post.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<div class='row'>
  <div class='col-md-4'>
    <%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>

    <div class='card'>
      <div class='card-header'>
        <h6 class='card-title mb-0'>New Post</h6>
      </div>
      <div class='card-body'>
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light authors'>
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/readers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light readers <%= controller_name %> <%= action_name %>'>
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/readers/home/index.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark mb-3 rounded-1">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MyBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'My Posts', posts_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <% if author_signed_in? %>
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class:"nav-link" %>
          <% else %>
            <%= link_to 'Sign In', author_session_path, class:"nav-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class='row'>
  <% @posts.each do |post| %>
    <div class='col-md-6 col-lg-4'>
      <div class="card post-card mb-3">
        <div class='header-image' style='background-image: url(<%= url_for(post.header_image) %>)'>
        </div>
        <div class="card-body d-flex flex-column">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"><%= truncate(post.description, length: 200) %></p>
          <%= link_to 'Read', blog_post_path(post), class: 'btn btn-primary mt-auto' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/readers/posts/show.html.erb
<div class='row'>
  <div class='col-lg-10 offset-lg-1'>
  <div><%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe, root_path, class: 'btn btn-dark mb-3 text-light' %></div>
    <div class="card post-card mb-5">
      <div class='header-image' style='background-image: url(<%= url_for (@post.header_image) %>)'></div>
      <div class="card-body">
        <div class='ps-5 pe-5 pt-4 pb-4'>
          <h1 class="card-title mb-5"><%= @post.title %></h1>
          <% @post.elements.each do |element| %>
            <% if element.image? %>
              <div class='image-element mb-5'>
                <%= image_tag(element.image) %>
              </div>
            <% else %>
              <div class='content-element mb-5'>
                <%= element.content %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>